//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LKS_Mart
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointHistory
    {
        public int id { get; set; }
        public int customer_id { get; set; }
        public Nullable<int> header_transaction_id { get; set; }
        public Nullable<int> point_gained { get; set; }
        public Nullable<int> point_deducted { get; set; }
        public int point_before { get; set; }
        public int point_after { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> last_updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual HeaderTransaction HeaderTransaction { get; set; }
    }
}
